model_data:
  train_data_dir: data/processed
  train_filename: Train_Dataset.csv
  test_data_dir: data/processed
  test_filename: Test_Dataset.csv

  target_data: line_item_value

  models_dir: models
  file_model: model_rf.pkl
  reports_dir: reports

estimators:
  RandomForestRegressor:
    params:
      criterion: mae
      max_depth: 10
      min_sample_leaf: 2
      min_sample_split: 8
      n_estimators: 80
      oob_score: true

RandomizedSearchCV:
  n_iter: 30
  scoring: r2
  verbose: 5
  cv: 5
  random_state: 180
  n_jobs: -1
  return_train_score: true
  params:
    n_estimators:
    - 5
    - 10
    - 20
    - 40
    - 80
    criterion:
    - absolute_error
    - friedman_mse
    - poisson
    - squared_error
    max_depth:
    - 2
    - 5
    - 10
    min_samples_split:
    - 2
    - 4
    - 8
    - 12
    min_samples_leaf:
    - 2
    - 4
    - 8
    - 10
reports:
  scores: reports/scores.json
  params: reports/params.json
